export const WATCHLIST_STATUS = {
  PLANNED: "PLANNED",
  WATCHING: "WATCHING",
  COMPLETED: "COMPLETED",
  DROPPED: "DROPPED",
};

export const WATCHLIST_STATUS_LABELS = {
  [WATCHLIST_STATUS.PLANNED]: "Want to Watch",
  [WATCHLIST_STATUS.WATCHING]: "Watching",
  [WATCHLIST_STATUS.COMPLETED]: "Completed",
  [WATCHLIST_STATUS.DROPPED]: "Dropped",
};

export const WATCHLIST_STATUS_COLORS = {
  [WATCHLIST_STATUS.PLANNED]:
    "bg-blue-600",

  [WATCHLIST_STATUS.WATCHING]:
    "bg-yellow-500",

  [WATCHLIST_STATUS.COMPLETED]:
    "bg-green-600",

  [WATCHLIST_STATUS.DROPPED]:
    "bg-red-600",
};

export const WATCHLIST_STATUS_OPTIONS = [
  WATCHLIST_STATUS.PLANNED,
  WATCHLIST_STATUS.WATCHING,
  WATCHLIST_STATUS.COMPLETED,
  WATCHLIST_STATUS.DROPPED,
];