import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
import { FaShieldAlt, FaTimes } from "react-icons/fa";

export default function Enable2FAModal({
  open,
  onClose,
  onVerify,
  qrCode,
}) {
  const [code, setCode] = useState("");

  if (!open) return null;

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      >
        <motion.div
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.9, opacity: 0 }}
          transition={{ duration: 0.2 }}
          className="w-full max-w-lg rounded-3xl border border-slate-800 bg-slate-900 p-8"
        >
          <div className="flex items-center justify-between">

            <div className="flex items-center gap-3">

              <div className="rounded-2xl bg-cyan-500/10 p-3 text-cyan-400">
                <FaShieldAlt size={20} />
              </div>

              <div>
                <h2 className="text-2xl font-bold text-white">
                  Enable Two-Factor Authentication
                </h2>

                <p className="text-sm text-slate-400">
                  Scan the QR code below using your authenticator app.
                </p>
              </div>

            </div>

            <button
              onClick={onClose}
              className="text-slate-400 hover:text-white"
            >
              <FaTimes size={20} />
            </button>

          </div>

          <div className="my-8 flex justify-center">

            {qrCode ? (
              <img
                src={qrCode}
                alt="QR Code"
                className="rounded-xl bg-white p-3"
              />
            ) : (
              <div className="flex h-64 w-64 items-center justify-center rounded-xl border border-dashed border-slate-700 text-slate-500">
                QR Code Loading...
              </div>
            )}

          </div>

          <p className="mb-4 text-center text-slate-400">
            Enter the 6-digit code generated by your authenticator app.
          </p>

          <input
            type="text"
            maxLength={6}
            value={code}
            onChange={(e) =>
              setCode(e.target.value.replace(/\D/g, ""))
            }
            placeholder="123456"
            className="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-center text-2xl tracking-[0.5em] text-white outline-none focus:border-cyan-500"
          />

          <div className="mt-8 flex justify-end gap-3">

            <button
              onClick={onClose}
              className="rounded-xl bg-slate-700 px-5 py-3 font-semibold hover:bg-slate-600"
            >
              Cancel
            </button>

            <button
              onClick={() => onVerify(code)}
              disabled={code.length !== 6}
              className="rounded-xl bg-cyan-500 px-6 py-3 font-semibold text-black hover:bg-cyan-400 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Verify & Enable
            </button>

          </div>

        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}